
# The service object will contain all our containers
services:
  backend: # Service name
    # This Dockerfile is what's used to build the container
    build: <path to backend dockerfile>
    # Port forwarding
    ports: 
      - '<computerport:containerport>'
    # Name your container
    container_name: <container name>

  frontend:
    build: <path to frontend dockerfile>
    ports: 
      - '<computerport:containerport>'
    container_name: <container name>
